# Generated by Django 5.2 on 2025-07-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_proveedor_fecha_creacion_proveedor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
