# Generated by Django 5.2 on 2025-06-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(choices=[('carbon_vegetal', 'Carbón Vegetal'), ('carbon_mineral', 'Carbón Mineral'), ('leña_dura', 'Leña Dura'), ('leña_suave', 'Leña Suave')], max_length=50),
        ),
    ]
