# Generated by Django 5.2 on 2025-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_producto_cantidad_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='productos'),
        ),
    ]
