# Generated by Django 5.2 on 2025-06-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula_o_ruc', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(choices=[('frecuente', 'Frecuente'), ('ocasional', 'Ocasional'), ('mayorista', 'Mayorista'), ('minorista', 'Minorista')], default='ocasional', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
