# Generated by Django 5.2 on 2025-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='inventario',
            name='total_pedidos',
            field=models.IntegerField(default=0, help_text='Acumulado de unidades pedidas'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='total_ventas',
            field=models.IntegerField(default=0, help_text='Acumulado de unidades vendidas'),
        ),
    ]
